services:
  - type: web
    name: almex-asistente-web
    env: static
    buildCommand: echo "No build needed for static site"
    staticPublishPath: ./web
    routes:
      - type: rewrite
        source: /*
        destination: /index.html